### ISSUE TITLE
Simplify the CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [charlizeli/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are several selectors sharing the font-family and the font-weight properties. Here is how you might simplify the code further,

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}
```

You can apply these properties to the body tag in this case, because all elements inside the body tag should inherit the properties. Otherwise, you can select multiple selectors to apply the properties to.
